/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasupervisionesunidad;

import classes.JDBConnection;
import classes.JGlobalVariables;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author INVENTARIOS
 */
public class JFrmHistorialSupervisiones extends javax.swing.JFrame {

    String id, clues, unidad, departamento, personaUno, personaDos, personaTres, personaCuatro, personaCinco, personaSeis, fechaSuperv;
    
    /**
     * Creates new form JFrmHistorialSupervisiones
     */
    public JFrmHistorialSupervisiones() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTHistorialSup = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtCLUES = new javax.swing.JTextField();
        jTxtUnidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtDepto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtFechaSuper = new javax.swing.JTextField();
        jTxtPersonaUno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtPersonaDos = new javax.swing.JTextField();
        jTxtPersonaTres = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtPersonaSeis = new javax.swing.JTextField();
        jTxtPersonaCinco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtPersonaCuatro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Historial de supervisiones");

        jTHistorialSup.setAutoCreateRowSorter(true);
        jTHistorialSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CLUES", "Unidad", "Departamento", "Persona 1", "Persona 2", "Persona 3", "Persona 4", "Persona 5", "Persona 6", "Fecha superv"
            }
        ));
        jTHistorialSup.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTHistorialSupAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTHistorialSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTHistorialSupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTHistorialSup);

        jButton1.setText("Ver reporte");

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("//Se tiene que generar el reporte con los datos de la DB");

        jButton2.setText("Cargar datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("CLUES:");

        jTxtCLUES.setEnabled(false);
        jTxtCLUES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCLUESActionPerformed(evt);
            }
        });

        jTxtUnidad.setEnabled(false);
        jTxtUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUnidadActionPerformed(evt);
            }
        });

        jLabel4.setText("Unidad:");

        jLabel5.setText("Deparmento:");

        jTxtDepto.setEnabled(false);

        jLabel6.setText("Fecha Superv:");

        jTxtFechaSuper.setEnabled(false);
        jTxtFechaSuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFechaSuperActionPerformed(evt);
            }
        });

        jTxtPersonaUno.setEnabled(false);
        jTxtPersonaUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPersonaUnoActionPerformed(evt);
            }
        });

        jLabel7.setText("Persona 1:");

        jLabel8.setText("Persona 2:");

        jTxtPersonaDos.setEnabled(false);
        jTxtPersonaDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPersonaDosActionPerformed(evt);
            }
        });

        jTxtPersonaTres.setEnabled(false);
        jTxtPersonaTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPersonaTresActionPerformed(evt);
            }
        });

        jLabel9.setText("Persona 3:");

        jTxtID.setEnabled(false);

        jLabel10.setText("ID");

        jLabel11.setText("Persona 6:");

        jTxtPersonaSeis.setEnabled(false);
        jTxtPersonaSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPersonaSeisActionPerformed(evt);
            }
        });

        jTxtPersonaCinco.setEnabled(false);
        jTxtPersonaCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPersonaCincoActionPerformed(evt);
            }
        });

        jLabel12.setText("Persona 5:");

        jTxtPersonaCuatro.setEnabled(false);
        jTxtPersonaCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPersonaCuatroActionPerformed(evt);
            }
        });

        jLabel13.setText("Persona 4:");

        jCheckBox1.setText("Modificar");

        jButton3.setText("Actualizar datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtFechaSuper)
                                    .addComponent(jTxtUnidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtCLUES, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtDepto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxtPersonaUno))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxtPersonaDos))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxtPersonaCuatro))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxtPersonaCinco))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxtPersonaSeis))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxtPersonaTres)))))
                                .addGap(191, 191, 191))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtCLUES, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtPersonaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtPersonaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTxtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPersonaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jTxtFechaSuper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtPersonaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtPersonaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtPersonaSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT idsupervision, clues_unidad, nombre_unidad, nombre_departamento, persona_uno, persona_dos, persona_tres, persona_cuatro, persona_cinco, persona_seis, fecha_super FROM supervision INNER JOIN departamento on supervision.id_departamento = departamento.iddepartamento;";

        JDBConnection.openConnection();
        JDBConnection.selectQuery(sql, jTHistorialSup);
        JDBConnection.closeConnection();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void cargarDatosTabla(){
        
    }
    
    
    
    private void jTxtCLUESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCLUESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCLUESActionPerformed

    private void jTxtFechaSuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFechaSuperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFechaSuperActionPerformed

    private void jTHistorialSupAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTHistorialSupAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHistorialSupAncestorAdded

    private void jTHistorialSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTHistorialSupMouseClicked
        // TODO add your handling code here:
        //clickTabla(this.jTHistorialSup);
        JGlobalVariables.setClues(jTHistorialSup.getValueAt(jTHistorialSup.getSelectedRow(), 1).toString());
        JGlobalVariables.setNombreDepartementoSup(jTHistorialSup.getValueAt(jTHistorialSup.getSelectedRow(), 3).toString());
        JGlobalVariables.setFechaSupervision(jTHistorialSup.getValueAt(jTHistorialSup.getSelectedRow(), 10).toString());
        JGlobalVariables.setNombreUnidad(jTHistorialSup.getValueAt(jTHistorialSup.getSelectedRow(), 2).toString());
        jTHistorialSup.getValueAt(jTHistorialSup.getSelectedRow(), 0);
        
                //JGlobalVariables.setIdDepartamento(jTHistorialSup.getValueAt(jTHistorialSup.getSelectedRow(),0));
        
        jTxtCLUES.setText(JGlobalVariables.getClues());
        jTxtDepto.setText(JGlobalVariables.getNombreDepartementoSup());
        jTxtFechaSuper.setText(JGlobalVariables.getFechaSupervision());
        jTxtUnidad.setText(JGlobalVariables.getNombreUnidad());
    }//GEN-LAST:event_jTHistorialSupMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jTxtUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUnidadActionPerformed

    private void jTxtPersonaUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPersonaUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPersonaUnoActionPerformed

    private void jTxtPersonaDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPersonaDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPersonaDosActionPerformed

    private void jTxtPersonaTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPersonaTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPersonaTresActionPerformed

    private void jTxtPersonaSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPersonaSeisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPersonaSeisActionPerformed

    private void jTxtPersonaCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPersonaCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPersonaCincoActionPerformed

    private void jTxtPersonaCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPersonaCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPersonaCuatroActionPerformed

    /**
     * @param evt
     * @param args the command line arguments
     */
    
    private void jTHistorialSupActionPerformed(java.awt.event.ActionEvent evt) {
        clickTabla(jTHistorialSup);
    }
    
    public void clickTabla(JTable tabla) {

        tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event){
                jTxtCLUES.setText(tabla.getValueAt(tabla.getSelectedRow(), 0).toString());
            }
        });
        
        
        
        id = tabla.getValueAt(1, tabla.getSelectedColumn()).toString();
        jTxtCLUES.setText(id);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmHistorialSupervisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmHistorialSupervisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmHistorialSupervisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmHistorialSupervisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmHistorialSupervisiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTHistorialSup;
    private javax.swing.JTextField jTxtCLUES;
    private javax.swing.JTextField jTxtDepto;
    private javax.swing.JTextField jTxtFechaSuper;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtPersonaCinco;
    private javax.swing.JTextField jTxtPersonaCuatro;
    private javax.swing.JTextField jTxtPersonaDos;
    private javax.swing.JTextField jTxtPersonaSeis;
    private javax.swing.JTextField jTxtPersonaTres;
    private javax.swing.JTextField jTxtPersonaUno;
    private javax.swing.JTextField jTxtUnidad;
    // End of variables declaration//GEN-END:variables
}
