/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasupervisionesunidad;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import classes.JDBConnection;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import classes.JGlobalVariables;
import java.io.File;
import java.util.Locale;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 * Clase principal para realizar una Nueva Supervisión.
 * @author INVENTARIOS
 */
public class JFrmNuevaSupervision extends javax.swing.JFrame {
    /**
     * Creates new form JFrmNuevaSupervision
     */    
    public JFrmNuevaSupervision() {
        initComponents();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        dpFechaSupervision.setFormats(formatoFecha);
        txtPersona1.setEnabled(true);               
        txtPersona2.setEnabled(false);
        txtPersona3.setEnabled(false);
        txtPersona4.setEnabled(false);
        txtPersona5.setEnabled(false);
        txtPersona6.setEnabled(false);
        jTxtCargoPersona1.setEnabled(true);
        jTxtCargoPersona2.setEnabled(false);
        jTxtCargoPersona3.setEnabled(false);
        jTxtCargoPersona4.setEnabled(false);
        jTxtCargoPersona5.setEnabled(false);
        jTxtCargoPersona6.setEnabled(false);
        fillComboBoxWithNoValue(5);
        //abrir coneccion a SQLite
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compoundPainter1 = new org.jdesktop.swingx.painter.CompoundPainter();
        defaultUserNameStore1 = new org.jdesktop.swingx.auth.DefaultUserNameStore();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dpFechaSupervision = new org.jdesktop.swingx.JXDatePicker();
        txtCLUES = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtActividadesSup = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivoSupervision = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbNumPersonas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbDepartamento = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPersona1 = new javax.swing.JTextField();
        txtPersona2 = new javax.swing.JTextField();
        txtPersona3 = new javax.swing.JTextField();
        txtPersona4 = new javax.swing.JTextField();
        txtPersona5 = new javax.swing.JTextField();
        txtPersona6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTxtCargoPersona1 = new javax.swing.JTextField();
        jTxtCargoPersona2 = new javax.swing.JTextField();
        jTxtCargoPersona3 = new javax.swing.JTextField();
        jTxtCargoPersona4 = new javax.swing.JTextField();
        jTxtCargoPersona5 = new javax.swing.JTextField();
        jTxtCargoPersona6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("- Nueva Supervisión -");

        jContenedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Fecha de supervisión");

        dpFechaSupervision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpFechaSupervisionActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Clave CLUES");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Motivo de supervisión");

        jLabel5.setText("Descrpción de actividades");

        txtActividadesSup.setColumns(20);
        txtActividadesSup.setRows(5);
        jScrollPane2.setViewportView(txtActividadesSup);

        txtMotivoSupervision.setColumns(20);
        txtMotivoSupervision.setRows(5);
        jScrollPane1.setViewportView(txtMotivoSupervision);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nombre unidad");

        jLabel7.setText("Número de personas que acuden a la supervisión");

        cbNumPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 PERSONA", "2 PERSONAS", "3 PERSONAS", "4 PERSONAS", "5 PERSONAS", "6 PERSONAS" }));
        cbNumPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNumPersonasActionPerformed(evt);
            }
        });

        jLabel8.setText("Departamento");

        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATENCION INTEGRAL", "EPIDEMIOLOGIA", "ADMINISTRACION", "DEPARTAMENTOS MIXTOS" }));
        cbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartamentoActionPerformed(evt);
            }
        });

        jLabel9.setText("Persona 1");

        jLabel10.setText("Persona 2");

        jLabel11.setText("Persona 3");

        jLabel12.setText("Persona 4");

        jLabel13.setText("Persona 5");

        jLabel14.setText("Persona 6");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("<html>Generar reporte</br> y guardar.</html>");
        jButton1.setActionCommand("Generar reporte y guardar.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Cargo");

        jTxtCargoPersona3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCargoPersona3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Cargo");

        jLabel17.setText("Cargo");

        jLabel18.setText("Cargo");

        jLabel19.setText("Cargo");

        jLabel20.setText("Cargo");

        javax.swing.GroupLayout jContenedorLayout = new javax.swing.GroupLayout(jContenedor);
        jContenedor.setLayout(jContenedorLayout);
        jContenedorLayout.setHorizontalGroup(
            jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jContenedorLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jContenedorLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2))
                        .addGroup(jContenedorLayout.createSequentialGroup()
                            .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jContenedorLayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1)
                                .addComponent(txtUnidad))))
                    .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jContenedorLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbNumPersonas, 0, 147, Short.MAX_VALUE))
                        .addGroup(jContenedorLayout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jContenedorLayout.createSequentialGroup()
                            .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jContenedorLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPersona6))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jContenedorLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPersona5))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jContenedorLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPersona4))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jContenedorLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPersona3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jContenedorLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPersona2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jContenedorLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtCargoPersona1)
                                .addComponent(jTxtCargoPersona2)
                                .addComponent(jTxtCargoPersona3)
                                .addComponent(jTxtCargoPersona4)
                                .addComponent(jTxtCargoPersona5)
                                .addComponent(jTxtCargoPersona6))))
                    .addGroup(jContenedorLayout.createSequentialGroup()
                        .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCLUES, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(dpFechaSupervision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jContenedorLayout.setVerticalGroup(
            jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dpFechaSupervision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCLUES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTxtCargoPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCargoPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(8, 8, 8)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPersona3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCargoPersona3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(8, 8, 8)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPersona4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCargoPersona4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPersona5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCargoPersona5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPersona6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCargoPersona6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollPane3.setViewportView(jContenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCargoPersona3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCargoPersona3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCargoPersona3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String fechaDMY = sdf.format(dpFechaSupervision.getDate());

        JGlobalVariables.setFechaSupervision(fechaDMY);
        JGlobalVariables.setClues(txtCLUES.getText());
        JGlobalVariables.setDescripcionActividades(txtActividadesSup.getText());
        JGlobalVariables.setIdDepartamento(cbDepartamento.getSelectedIndex()+1);

        int idDepartamento = 0;

        try {
            idDepartamento = cbDepartamento.getSelectedIndex()+1;
            JDBConnection.openConnection();
            JDBConnection.insertQuery(fechaDMY, txtCLUES.getText(),txtActividadesSup.getText(),
                    txtUnidad.getText(),txtMotivoSupervision.getText(), 
                    String.valueOf(cbNumPersonas.getSelectedItem()),txtPersona1.getText(),
                    txtPersona2.getText(),txtPersona3.getText(),txtPersona4.getText(),
                    txtPersona5.getText(),txtPersona6.getText(),idDepartamento,
                    jTxtCargoPersona1.getText(),jTxtCargoPersona2.getText(),
                    jTxtCargoPersona3.getText(),jTxtCargoPersona4.getText(),
                    jTxtCargoPersona5.getText(), jTxtCargoPersona6.getText());
            generarReporte(String.valueOf(cbNumPersonas.getSelectedItem()).substring(0, 1));
            JDBConnection.closeConnection();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error: " +e.getMessage() + "\n Causas: "+e.getCause());
        }

        //generar metodo para crear reporte

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepartamentoActionPerformed

    private void cbNumPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNumPersonasActionPerformed
        // TODO add your handling code here:
        //String itemCb = String.valueOf(jComboBox1.getSelectedItem());
        switch (cbNumPersonas.getSelectedIndex()) {
            case 0:
            //una
            fillComboBoxWithNoValue(5);
            txtPersona1.setEnabled(true);
            jTxtCargoPersona1.setEnabled(true);
            txtPersona2.setEnabled(false);
            jTxtCargoPersona2.setEnabled(false);
            txtPersona3.setEnabled(false);
            jTxtCargoPersona3.setEnabled(false);
            txtPersona4.setEnabled(false);
            jTxtCargoPersona4.setEnabled(false);
            txtPersona5.setEnabled(false);
            jTxtCargoPersona5.setEnabled(false);
            txtPersona6.setEnabled(false);
            jTxtCargoPersona6.setEnabled(false);
            break;
            case 1:
            //dos
            fillComboBoxWithNoValue(4);
            txtPersona1.setEnabled(true);
            jTxtCargoPersona1.setEnabled(true);
            txtPersona2.setEnabled(true);
            jTxtCargoPersona2.setEnabled(true);
            txtPersona3.setEnabled(false);
            jTxtCargoPersona3.setEnabled(false);
            txtPersona4.setEnabled(false);
            jTxtCargoPersona4.setEnabled(false);
            txtPersona5.setEnabled(false);
            jTxtCargoPersona5.setEnabled(false);
            txtPersona6.setEnabled(false);
            jTxtCargoPersona6.setEnabled(false);
            break;
            case 2:
            //tres
            fillComboBoxWithNoValue(3);
            txtPersona1.setEnabled(true);
            jTxtCargoPersona1.setEnabled(true);
            txtPersona2.setEnabled(true);
            jTxtCargoPersona2.setEnabled(true);
            txtPersona3.setEnabled(true);
            jTxtCargoPersona3.setEnabled(true);
            txtPersona4.setEnabled(false);
            jTxtCargoPersona4.setEnabled(false);
            txtPersona5.setEnabled(false);
            jTxtCargoPersona5.setEnabled(false);
            txtPersona6.setEnabled(false);
            jTxtCargoPersona6.setEnabled(false);
            break;
            case 3:
            //cuatro
            fillComboBoxWithNoValue(2);
            txtPersona1.setEnabled(true);
            jTxtCargoPersona1.setEnabled(true);
            txtPersona2.setEnabled(true);
            jTxtCargoPersona2.setEnabled(true);
            txtPersona3.setEnabled(true);
            jTxtCargoPersona3.setEnabled(true);
            txtPersona4.setEnabled(true);
            jTxtCargoPersona4.setEnabled(true);
            txtPersona5.setEnabled(false);
            txtPersona6.setEnabled(false);
            jTxtCargoPersona5.setEnabled(false);
            jTxtCargoPersona6.setEnabled(false);
            break;
            case 4:
            //cinco
            fillComboBoxWithNoValue(1);
            txtPersona1.setEnabled(true);
            jTxtCargoPersona1.setEnabled(true);
            txtPersona2.setEnabled(true);
            jTxtCargoPersona2.setEnabled(true);
            txtPersona3.setEnabled(true);
            jTxtCargoPersona3.setEnabled(true);
            txtPersona4.setEnabled(true);
            jTxtCargoPersona4.setEnabled(true);
            txtPersona5.setEnabled(true);
            jTxtCargoPersona5.setEnabled(true);
            txtPersona6.setEnabled(false);
            jTxtCargoPersona6.setEnabled(false);
            break;
            case 5:
            //seis
            fillComboBoxWithNoValue(6);
            txtPersona1.setEnabled(true);
            txtPersona2.setEnabled(true);
            txtPersona3.setEnabled(true);
            txtPersona4.setEnabled(true);
            txtPersona5.setEnabled(true);
            txtPersona6.setEnabled(true);
            jTxtCargoPersona1.setEnabled(true);
            jTxtCargoPersona2.setEnabled(true);
            jTxtCargoPersona3.setEnabled(true);
            jTxtCargoPersona4.setEnabled(true);
            jTxtCargoPersona5.setEnabled(true);
            jTxtCargoPersona6.setEnabled(true);
            break;
            default:
            JOptionPane.showMessageDialog(null,"Prueba de mensaje");
            break;
        }
    }//GEN-LAST:event_cbNumPersonasActionPerformed

    private void dpFechaSupervisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpFechaSupervisionActionPerformed
        // TODO add your handling code here:
        //cambiar el formato de fecha a DD/mm/YYYY
    }//GEN-LAST:event_dpFechaSupervisionActionPerformed

    
    /**
     * <code>fillComboBoxWithNoValue</code> se utiliza para rellenar elementos <code>TextField</code> del GUI.
     * @param cantidad de acuerdo a la cantidad, se puede "limpiar" los <code>TextField</code>. Rango: 1 a 6.
     */
    private void fillComboBoxWithNoValue(int cantidad){
        switch (cantidad) {
            case 6:
                txtPersona1.setText(String.valueOf(""));
                txtPersona2.setText(String.valueOf(""));
                txtPersona3.setText(String.valueOf(""));
                txtPersona4.setText(String.valueOf(""));
                txtPersona5.setText(String.valueOf(""));
                txtPersona6.setText(String.valueOf(""));        
                jTxtCargoPersona1.setText(String.valueOf(""));
                jTxtCargoPersona2.setText(String.valueOf(""));
                jTxtCargoPersona3.setText(String.valueOf(""));
                jTxtCargoPersona4.setText(String.valueOf(""));
                jTxtCargoPersona5.setText(String.valueOf(""));
                jTxtCargoPersona6.setText(String.valueOf(""));
                break;
            case 5: //cinco personas
                txtPersona2.setText("--");
                txtPersona3.setText("--");
                txtPersona4.setText("--");
                txtPersona5.setText("--");
                txtPersona6.setText("--");
                jTxtCargoPersona2.setText("--");
                jTxtCargoPersona3.setText("--");
                jTxtCargoPersona4.setText("--");
                jTxtCargoPersona5.setText("--");
                jTxtCargoPersona6.setText("--");
                break;
            case 4:
                txtPersona2.setText("");
                txtPersona3.setText("--");
                txtPersona4.setText("--");
                txtPersona5.setText("--");
                txtPersona6.setText("--");
                jTxtCargoPersona2.setText("");
                jTxtCargoPersona3.setText("--");
                jTxtCargoPersona4.setText("--");
                jTxtCargoPersona5.setText("--");
                jTxtCargoPersona6.setText("--");                
                break;
            case 3: 
                txtPersona2.setText("");
                txtPersona3.setText("");                
                txtPersona4.setText("--");
                txtPersona5.setText("--");
                txtPersona6.setText("--"); 
                jTxtCargoPersona2.setText("");
                jTxtCargoPersona3.setText("");
                jTxtCargoPersona4.setText("--");
                jTxtCargoPersona5.setText("--");
                jTxtCargoPersona6.setText("--");                 
                break;
            case 2:
                txtPersona2.setText("");
                txtPersona3.setText("");                
                txtPersona4.setText("");                
                txtPersona5.setText("--");
                txtPersona6.setText("--");     
                jTxtCargoPersona2.setText("");
                jTxtCargoPersona3.setText("");
                jTxtCargoPersona4.setText("");
                jTxtCargoPersona5.setText("--");
                jTxtCargoPersona6.setText("--");                 
                break;
            case 1:
                txtPersona2.setText("");
                txtPersona3.setText("");                
                txtPersona4.setText("");                
                txtPersona5.setText("");                
                txtPersona6.setText("--");      
                jTxtCargoPersona2.setText("");
                jTxtCargoPersona3.setText("");
                jTxtCargoPersona4.setText("");
                jTxtCargoPersona5.setText("");
                jTxtCargoPersona6.setText("--");                 
                break;
            default: break;
        }
    }
    /**
     * Metodo no servible, utilizar <code>generarReporte(String numeroDePersonas)</code> en su lugar.
     */
    private void generarReporte(){
        try {
        String rutaGuardarReporte = JGlobalVariables.getRutaGuardadoReporte();
        String rutaPatron = "C:\\Users\\usuario\\Downloads\\sistemasupervisionesunidad-final\\sistemasupervisionesunidad-final\\src\\sistemasupervisionesunidad\\reportes\\RSupervisionAIUnaPersona.jrxml"; //Jrxml
        //String rutaPatron = "C:/supervisionesssh/repo/RSupervisionAIUnaPersona.jrxml";
        String rutaJasperFile = "C:\\Users\\usuario\\Downloads\\sistemasupervisionesunidad-final\\sistemasupervisionesunidad-final\\src\\sistemasupervisionesunidad\\reportes\\RSupervisionAIUnaPersona.jasper";
        //String rutaJasperFile = "C:/supervisionesssh/repo/RSupervisionAIUnaPersona.jasper";
        
        JasperCompileManager.compileReportToFile(rutaPatron, rutaJasperFile);
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("clues_unidad", this.txtCLUES.getText());
        parameters.put("descripcion_actividad", this.txtActividadesSup.getText());
        //File reportPattern = new File(rutaPatron);
        //JasperDesign jasperDesign = JRXmlLoader.load(reportPattern);
        //JasperReport reporte = JasperCompileManager.compileReport(jasperDesign);
        //JasperPrint impresion = JasperFillManager.fillReport(rutaJasperFile, parameters,JDBConnection.getConnection());
        JasperPrint impresion = JasperFillManager.fillReport(rutaJasperFile, parameters,new JREmptyDataSource());
        JasperExportManager.exportReportToPdfFile(impresion, rutaGuardarReporte);        
        JasperViewer.viewReport(impresion, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error: " +e.getMessage()+"\n Causas: "+e.getCause()+e.getStackTrace());
    }
           
   }    
    
    
    /**
     * Método para generar reporte de acuerdo al número de personas ingresadas.
     * @param numeroDePersonas Número de personas, se obtiene en <code>String</code>, después se procesa
     * para cambiarlo a int y utilizarlo en un <code>switch</code>.
     */
    private void generarReporte(String numeroDePersonas){
        Integer.parseInt(String.valueOf(numeroDePersonas));
        String rutaGuardarReporte = JGlobalVariables.getRutaGuardadoReporte();
        //String rutaJRXML = "C:\\supervisionesssh\\repo\\jsp\\";
        //String rutaJasperFile = "C:\\supervisionesssh\\repo\\jsp\\";
        String rutaJRXML = JGlobalVariables.getRutaJRXml();
        String rutaJasperFile = JGlobalVariables.getRutaJasperFile();
        
        try{
            switch(Integer.parseInt(String.valueOf(numeroDePersonas))){
            case 1:
                rutaJRXML+=JGlobalVariables.getReporteJRXMLPersona(0);
                rutaJasperFile+=JGlobalVariables.getJasperReportFile(0);
                JasperCompileManager.compileReportToFile(rutaJRXML, rutaJasperFile);
                Map<String, Object> parameters = new HashMap<>();
                parameters.put("clues_unidad", this.txtCLUES.getText());
                parameters.put("descripcion_actividad", this.txtActividadesSup.getText());                
                parameters.put("depto_supervisor", String.valueOf(cbDepartamento.getSelectedItem()));
                parameters.put("fecha_supervision",JGlobalVariables.getFechaSupervision());
                parameters.put("persona_uno",txtPersona1.getText());
                parameters.put("cargo_persona_uno",jTxtCargoPersona1.getText());
                JasperPrint impresion = JasperFillManager.fillReport(rutaJasperFile, parameters,new JREmptyDataSource());
                JasperExportManager.exportReportToPdfFile(impresion, rutaGuardarReporte);        
                JasperViewer.viewReport(impresion, false);
                parameters = null;
                break;
            case 2:
                rutaJRXML+=JGlobalVariables.getReporteJRXMLPersona(1);
                rutaJasperFile+=JGlobalVariables.getJasperReportFile(1);
                JasperCompileManager.compileReportToFile(rutaJRXML, rutaJasperFile);
                Map<String, Object> parameters2 = new HashMap<>();
                parameters2.put("clues_unidad", this.txtCLUES.getText());
                parameters2.put("descripcion_actividad", this.txtActividadesSup.getText());                
                parameters2.put("depto_supervisor", String.valueOf(cbDepartamento.getSelectedItem()));
                parameters2.put("fecha_supervision",JGlobalVariables.getFechaSupervision());
                parameters2.put("persona_uno",txtPersona1.getText());
                parameters2.put("cargo_persona_uno",jTxtCargoPersona1.getText());
                parameters2.put("persona_dos",txtPersona2.getText());
                parameters2.put("cargo_persona_dos",jTxtCargoPersona2.getText());
                JasperPrint impresion2 = JasperFillManager.fillReport(rutaJasperFile, parameters2,new JREmptyDataSource());
                JasperExportManager.exportReportToPdfFile(impresion2, rutaGuardarReporte);        
                JasperViewer.viewReport(impresion2, false);
                parameters2 = null;
                break;
            case 3:
                rutaJRXML+=JGlobalVariables.getReporteJRXMLPersona(2);
                rutaJasperFile+=JGlobalVariables.getJasperReportFile(2);
                JasperCompileManager.compileReportToFile(rutaJRXML, rutaJasperFile);
                Map<String, Object> parameters3 = new HashMap<>();
                parameters3.put("clues_unidad", this.txtCLUES.getText());
                parameters3.put("descripcion_actividad", this.txtActividadesSup.getText());                
                parameters3.put("depto_supervisor", String.valueOf(cbDepartamento.getSelectedItem()));
                parameters3.put("fecha_supervision",JGlobalVariables.getFechaSupervision());
                parameters3.put("persona_uno",txtPersona1.getText());
                parameters3.put("cargo_persona_uno",jTxtCargoPersona1.getText());
                parameters3.put("persona_dos",txtPersona2.getText());
                parameters3.put("cargo_persona_dos",jTxtCargoPersona2.getText());                
                parameters3.put("persona_tres",txtPersona3.getText());
                parameters3.put("cargo_persona_tres",jTxtCargoPersona3.getText());                                
                JasperPrint impresion3 = JasperFillManager.fillReport(rutaJasperFile, parameters3,new JREmptyDataSource());
                JasperExportManager.exportReportToPdfFile(impresion3, rutaGuardarReporte);        
                JasperViewer.viewReport(impresion3, false);
                parameters3 = null;                
                break;
            case 4:
                rutaJRXML+=JGlobalVariables.getReporteJRXMLPersona(3);
                rutaJasperFile+=JGlobalVariables.getJasperReportFile(3);
                JasperCompileManager.compileReportToFile(rutaJRXML, rutaJasperFile);
                Map<String, Object> parameters4 = new HashMap<>();
                parameters4.put("clues_unidad", this.txtCLUES.getText());
                parameters4.put("descripcion_actividad", this.txtActividadesSup.getText());                
                parameters4.put("depto_supervisor", String.valueOf(cbDepartamento.getSelectedItem()));
                parameters4.put("fecha_supervision",JGlobalVariables.getFechaSupervision());
                parameters4.put("persona_uno",txtPersona1.getText());
                parameters4.put("cargo_persona_uno",jTxtCargoPersona1.getText());
                parameters4.put("persona_dos",txtPersona2.getText());
                parameters4.put("cargo_persona_dos",jTxtCargoPersona2.getText());                
                parameters4.put("persona_tres",txtPersona3.getText());
                parameters4.put("cargo_persona_tres",jTxtCargoPersona3.getText());                                                
                parameters4.put("persona_cuatro",txtPersona4.getText());
                parameters4.put("cargo_persona_cuatro",jTxtCargoPersona4.getText());
                JasperPrint impresion4 = JasperFillManager.fillReport(rutaJasperFile, parameters4,new JREmptyDataSource());
                JasperExportManager.exportReportToPdfFile(impresion4, rutaGuardarReporte);        
                JasperViewer.viewReport(impresion4, false);
                parameters4 = null;                     
                break;
            case 5:
                rutaJRXML+=JGlobalVariables.getReporteJRXMLPersona(4);
                rutaJasperFile+=JGlobalVariables.getJasperReportFile(4);
                JasperCompileManager.compileReportToFile(rutaJRXML, rutaJasperFile);
                Map<String, Object> parameters5 = new HashMap<>();
                parameters5.put("clues_unidad", this.txtCLUES.getText());
                parameters5.put("descripcion_actividad", this.txtActividadesSup.getText());                
                parameters5.put("depto_supervisor", String.valueOf(cbDepartamento.getSelectedItem()));
                parameters5.put("fecha_supervision",JGlobalVariables.getFechaSupervision());
                parameters5.put("persona_uno",txtPersona1.getText());
                parameters5.put("cargo_persona_uno",jTxtCargoPersona1.getText());
                parameters5.put("persona_dos",txtPersona2.getText());
                parameters5.put("cargo_persona_dos",jTxtCargoPersona2.getText());                
                parameters5.put("persona_tres",txtPersona3.getText());
                parameters5.put("cargo_persona_tres",jTxtCargoPersona3.getText());                                                
                parameters5.put("persona_cuatro",txtPersona4.getText());
                parameters5.put("cargo_persona_cuatro",jTxtCargoPersona4.getText());                
                parameters5.put("persona_cinco",txtPersona5.getText());
                parameters5.put("cargo_persona_cinco",jTxtCargoPersona5.getText());                                
                JasperPrint impresion5 = JasperFillManager.fillReport(rutaJasperFile, parameters5,new JREmptyDataSource());
                JasperExportManager.exportReportToPdfFile(impresion5, rutaGuardarReporte);        
                JasperViewer.viewReport(impresion5, false);
                parameters5 = null;                  
                break;
            case 6:
                rutaJRXML+=JGlobalVariables.getReporteJRXMLPersona(5);
                rutaJasperFile+=JGlobalVariables.getJasperReportFile(5);
                JasperCompileManager.compileReportToFile(rutaJRXML, rutaJasperFile);
                Map<String, Object> parameters6 = new HashMap<>();
                parameters6.put("clues_unidad", this.txtCLUES.getText());
                parameters6.put("descripcion_actividad", this.txtActividadesSup.getText());                
                parameters6.put("depto_supervisor", String.valueOf(cbDepartamento.getSelectedItem()));
                parameters6.put("fecha_supervision",JGlobalVariables.getFechaSupervision());
                parameters6.put("persona_uno",txtPersona1.getText());
                parameters6.put("cargo_persona_uno",jTxtCargoPersona1.getText());
                parameters6.put("persona_dos",txtPersona2.getText());
                parameters6.put("cargo_persona_dos",jTxtCargoPersona2.getText());                
                parameters6.put("persona_tres",txtPersona3.getText());
                parameters6.put("cargo_persona_tres",jTxtCargoPersona3.getText());                                                
                parameters6.put("persona_cuatro",txtPersona4.getText());
                parameters6.put("cargo_persona_cuatro",jTxtCargoPersona4.getText());                
                parameters6.put("persona_cinco",txtPersona5.getText());
                parameters6.put("cargo_persona_cinco",jTxtCargoPersona5.getText());  
                parameters6.put("persona_seis",txtPersona6.getText());
                parameters6.put("cargo_persona_seis",jTxtCargoPersona6.getText());                  
                JasperPrint impresion6 = JasperFillManager.fillReport(rutaJasperFile, parameters6,new JREmptyDataSource());
                JasperExportManager.exportReportToPdfFile(impresion6, rutaGuardarReporte);        
                JasperViewer.viewReport(impresion6, false);
                parameters6 = null;                  
                break;
            default: break;         
            }
        } catch(JRException e){
            System.out.print(e);
        }        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmNuevaSupervision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmNuevaSupervision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmNuevaSupervision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmNuevaSupervision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmNuevaSupervision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JComboBox<String> cbNumPersonas;
    private org.jdesktop.swingx.painter.CompoundPainter compoundPainter1;
    private org.jdesktop.swingx.auth.DefaultUserNameStore defaultUserNameStore1;
    private org.jdesktop.swingx.JXDatePicker dpFechaSupervision;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jContenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTxtCargoPersona1;
    private javax.swing.JTextField jTxtCargoPersona2;
    private javax.swing.JTextField jTxtCargoPersona3;
    private javax.swing.JTextField jTxtCargoPersona4;
    private javax.swing.JTextField jTxtCargoPersona5;
    private javax.swing.JTextField jTxtCargoPersona6;
    private javax.swing.JTextArea txtActividadesSup;
    private javax.swing.JTextField txtCLUES;
    private javax.swing.JTextArea txtMotivoSupervision;
    private javax.swing.JTextField txtPersona1;
    private javax.swing.JTextField txtPersona2;
    private javax.swing.JTextField txtPersona3;
    private javax.swing.JTextField txtPersona4;
    private javax.swing.JTextField txtPersona5;
    private javax.swing.JTextField txtPersona6;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
